#----------------------------------------------------------------------------
#
# Platform Game Engine Project by Wohlstand, a free platform for making games of platform genre
# Copyright (c) 2014-2019 Vitaly Novichkov <admin@wohlnet.ru>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#----------------------------------------------------------------------------
# Travis-CI building configuration file for Mac OS X Operating system
#                       created 2015-11-26
#----------------------------------------------------------------------------

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eZjlsg6iAuRaU2qiofJUOFT8qmomXTgy9IpfbuI4UOLQpz7bXq9CVCrCE2HhoPLEj08AjLvn60sBDJE3vX7TWVDYAS4/tNx2mcWbRjPSlI0uIIC1ehCKUFoPu8wH8eJZCrJUijyPBf7WbZ2uDCar+pgAbecv+Fi//jUk1i+W/Q0="

git:
  depth: 2

branches:
  only:
    - master
    - stable

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - QT_VER=5.10.1_static
        - QT_TARBALL=qt-5.10.1-static-ubuntu-14-04-x64-gcc6.tar.bz2
        - IS_COVERITY_SCAN=true
      addons:
        coverity_scan:
          project:
            name: "WohlSoft/PGE-Project"
            description: "PGE Project - a free and open source game engine to create games of platform genre"
          notification_email: admin@wohlnet.ru
          build_command:   "bash ./build.sh no-pause ninja noqt noeditor nocalibrator nogifs2png nopng2gifs nolazyfixtool nomanager nomaintainer nomusicplayer;"
          branch_pattern: master
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:ubuntu-sdk-team/ppa"
            - sourceline: "ppa:george-edison55/cmake-3.x"
          packages:
            - build-essential
            - "^libxcb.*"
            - libx11-dev
            - libx11-xcb-dev
            - libxcursor-dev
            - libxrender-dev
            - libxrandr-dev
            - libxext-dev
            - libxi-dev
            - libxss-dev
            - libxt-dev
            - libxv-dev
            - libxxf86vm-dev
            - libxinerama-dev
            - libxkbcommon-dev
            - libfontconfig1-dev
            - libasound2-dev
            - libpulse-dev
            - libdbus-1-dev
            - udev
            - mtdev-tools
            - webp
            - libudev-dev
            - libglm-dev
            - libwayland-dev
            - libegl1-mesa-dev
            - mesa-common-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libgles2-mesa
            - libgles2-mesa-dev
            - libmirclient-dev
            - libproxy-dev
            - ccache
            - gcc-6
            - g++-6
            - libc6
            - libstdc++6
            - cmake
            - ninja-build
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - QT_VER=5.10.1_static
        - QT_TARBALL=qt-5.10.1-static-ubuntu-14-04-x64-gcc6.tar.bz2
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:ubuntu-sdk-team/ppa"
          packages:
            - build-essential
            - "^libxcb.*"
            - libx11-dev
            - libx11-xcb-dev
            - libxcursor-dev
            - libxrender-dev
            - libxrandr-dev
            - libxext-dev
            - libxi-dev
            - libxss-dev
            - libxt-dev
            - libxv-dev
            - libxxf86vm-dev
            - libxinerama-dev
            - libxkbcommon-dev
            - libfontconfig1-dev
            - libasound2-dev
            - libpulse-dev
            - libdbus-1-dev
            - udev
            - mtdev-tools
            - webp
            - libudev-dev
            - libglm-dev
            - libwayland-dev
            - libegl1-mesa-dev
            - mesa-common-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libgles2-mesa
            - libgles2-mesa-dev
            - libmirclient-dev
            - libproxy-dev
            - ccache
            - gcc-6
            - g++-6
            - libc6
            - libstdc++6
            - cmake
            - ninja-build
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - QT_VER=5.12.4
        - QT_TARBALL=qt-5-12-4-static-macosx-10-14-5.tar.bz2
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      addons:
        homebrew:
          packages:
            - ninja
            - cmake
            - coreutils
            - binutils
            - gnu-sed
            - lftp
            - axel

before_install:
  - bash _common/travis-ci/before-install.sh

# install: true

before_script:
  - bash _common/travis-ci/before-script.sh

script:
  - bash _common/travis-ci/build.sh

after_success:
  - bash _common/travis-ci/upload.sh

